services:
  db:
    image: postgres:16-alpine
    container_name: linketinder_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: linketinder
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./01-initial.sql:/docker-entrypoint-initdb.d/01-initial.sql
      - ./02-populate.sql:/docker-entrypoint-initdb.d/02-populate.sql

volumes:
  pgdata: